#!/usr/bin/env python3
"""Run CLAM patching and GPU feature extraction.\n\nProject defaults:\n- Feature extraction uses x20 by default.\n- For the current project assumption, OpenSlide level 1 corresponds to x20.\n- Patch coordinates are generated by CLAM at patch_size=512, step_size=512.\n- UNI2-h crops x20 512-pixel tiles and resizes model input to 224.\n- ResNet50, UNI2-h, and CONCH1.5 all reuse the same x20 512-pixel CLAM patch coordinates.\n- CONCH1.5/TITAN uses x20 512-pixel tiles and model input size 448 in CLAM.\n"""

from __future__ import annotations

import argparse
import csv
import os
import subprocess
import sys
from pathlib import Path


def run(cmd, cwd=None, env=None, check=True):
    print("\n$ " + " ".join(str(x) for x in cmd))
    result = subprocess.run(cmd, cwd=cwd, env=env, check=check)
    return result.returncode



def sanitize_thread_env(env: dict[str, str], default: str = "1") -> None:
    for name in ("OMP_NUM_THREADS", "MKL_NUM_THREADS", "OPENBLAS_NUM_THREADS", "NUMEXPR_NUM_THREADS"):
        value = env.get(name, "").strip()
        if not value or not value.isdigit() or int(value) < 1:
            env[name] = default

def workspace_root() -> Path:
    return Path(__file__).resolve().parent.parent


def read_expected_slide_names(index_csv: Path, slide_ext: str) -> list[str]:
    with index_csv.open("r", encoding="utf-8-sig", newline="") as f:
        reader = csv.DictReader(f)
        if reader.fieldnames is None:
            raise RuntimeError(f"Empty index CSV: {index_csv}")
        name_col = "slide_id" if "slide_id" in reader.fieldnames else "filename"
        if name_col not in reader.fieldnames:
            name_col = reader.fieldnames[0]
        names = []
        for row in reader:
            name = row[name_col].strip()
            if not name:
                continue
            if not name.lower().endswith(slide_ext.lower()):
                name += slide_ext
            names.append(name)
    return names


def build_readable_slide_process_list(
    source_dir: Path,
    patch_root: Path,
    slide_ext: str,
    expected_slide_index: Path | None = None,
) -> tuple[Path, Path, int, int, int]:
    """Create a CLAM process_list containing only slides OpenSlide can open."""
    import openslide

    preflight_dir = patch_root / "preflight"
    preflight_dir.mkdir(parents=True, exist_ok=True)
    process_list = preflight_dir / "process_list_readable_slides.csv"
    bad_report = preflight_dir / "unreadable_slides.csv"
    bad_names = preflight_dir / "unreadable_slides_recopy_list.txt"
    missing_report = preflight_dir / "missing_expected_slides.txt"

    available = {
        p.name: p
        for p in source_dir.iterdir()
        if p.is_file() and p.name.lower().endswith(slide_ext.lower())
    }
    if expected_slide_index is not None:
        expected_names = read_expected_slide_names(expected_slide_index, slide_ext)
        missing_names = [name for name in expected_names if name not in available]
        slide_paths = [available[name] for name in expected_names if name in available]
    else:
        expected_names = []
        missing_names = []
        slide_paths = [available[name] for name in sorted(available)]
    good_rows = []
    bad_rows = []

    missing_report.write_text(
        "\n".join(missing_names) + ("\n" if missing_names else ""),
        encoding="utf-8",
    )

    print(f"\nPreflight checking {len(slide_paths)} slide files with OpenSlide...")
    if expected_slide_index is not None:
        print(f"Expected slide index: {expected_slide_index}")
        print(f"Expected slides: {len(expected_names)}")
        print(f"Missing expected slides: {len(missing_names)}")
    for i, path in enumerate(slide_paths, 1):
        try:
            slide = openslide.open_slide(str(path))
            dimensions = slide.dimensions
            level_count = slide.level_count
            slide.close()
            good_rows.append(
                {
                    "slide_id": path.name,
                    "process": 1,
                    "status": "readable",
                    "width": dimensions[0],
                    "height": dimensions[1],
                    "level_count": level_count,
                    "size_bytes": path.stat().st_size,
                }
            )
        except Exception as exc:
            bad_rows.append(
                {
                    "slide_id": path.name,
                    "status": "likely_corrupt_or_incomplete",
                    "error_type": exc.__class__.__name__,
                    "error": str(exc),
                    "size_bytes": path.stat().st_size if path.exists() else "",
                    "path": str(path),
                    "recommendation": "recopy_this_slide",
                }
            )
            print(f"  BAD WSI - recopy recommended [{i}/{len(slide_paths)}]: {path.name} ({exc.__class__.__name__}: {exc})")

    with process_list.open("w", encoding="utf-8", newline="") as f:
        fieldnames = ["slide_id", "process", "status", "width", "height", "level_count", "size_bytes"]
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(good_rows)

    with bad_report.open("w", encoding="utf-8", newline="") as f:
        fieldnames = ["slide_id", "status", "error_type", "error", "size_bytes", "path", "recommendation"]
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(bad_rows)

    with bad_names.open("w", encoding="utf-8") as f:
        for row in bad_rows:
            f.write(row["slide_id"] + "\n")

    print(f"Preflight readable slides: {len(good_rows)}")
    print(f"Preflight unreadable slides: {len(bad_rows)}")
    print(f"Missing expected slides: {len(missing_names)}")
    print(f"CLAM process_list: {process_list}")
    print(f"Unreadable report: {bad_report}")
    print(f"Recopy list: {bad_names}")
    print(f"Missing expected list: {missing_report}")
    if bad_rows:
        print("WARNING: Some WSI files could not be opened by OpenSlide/PIL and are marked likely_corrupt_or_incomplete; recopy them later.")
    if not good_rows:
        raise RuntimeError(f"No readable slides found in {source_dir}")

    return process_list, bad_report, len(good_rows), len(bad_rows), len(missing_names)

def main() -> None:
    root = workspace_root()
    parser = argparse.ArgumentParser()
    parser.add_argument("--dataset", default="SARC")
    parser.add_argument("--source_dir", type=Path, required=True, help="External directory containing raw WSI files; raw data should not be stored inside this code repository.")
    parser.add_argument("--clam_dir", type=Path, default=Path(__file__).resolve().parent / "third_party" / "CLAM")
    parser.add_argument("--results_root", type=Path, required=True, help="External directory for patches/features; feature outputs should not be stored inside this code repository.")
    parser.add_argument("--checkpoints_root", type=Path, required=True, help="External directory containing encoder weights; encoder weights are not included in this repository.")
    parser.add_argument("--patch_size", type=int, default=512)
    parser.add_argument("--step_size", type=int, default=512)
    parser.add_argument("--patch_level", type=int, default=1, help="Default level 1 for x20 on this project; confirm OpenSlide level mapping per dataset.")
    parser.add_argument("--magnification_label", default="20x", help="Folder label only, default 20x for UNI2-h/CONCH1.5.")
    parser.add_argument("--batch_size", type=int, default=256)
    parser.add_argument("--slide_ext", default=".svs")
    parser.add_argument("--num_workers", type=int, default=4)
    parser.add_argument("--device", default="cuda", choices=["cuda", "cpu", "auto"])
    parser.add_argument("--no_amp", action="store_true", help="Disable CUDA mixed precision feature extraction.")
    parser.add_argument("--encoders", nargs="+", default=["resnet50_trunc", "uni_v2", "conch_v1_5"])
    parser.add_argument("--skip_patching", action="store_true")
    parser.add_argument("--skip_preflight", action="store_true")
    parser.add_argument(
        "--expected_slide_index",
        type=Path,
        default=None,
        help="Optional CSV of expected slides; missing/unreadable slides are reported before patching.",
    )
    parser.add_argument("--stitch", action="store_true")
    args = parser.parse_args()

    sanitize_thread_env(os.environ)

    source_dir = args.source_dir
    expected_slide_index = args.expected_slide_index
    default_index = root / "data" / f"{args.dataset}_slides_file_index.csv"
    if expected_slide_index is None and default_index.exists():
        expected_slide_index = default_index
    level_label = f"level{args.patch_level}_{args.magnification_label}"
    patch_root = (
        args.results_root
        / "clam_patches"
        / args.dataset
        / level_label
        / f"patch{args.patch_size}_step{args.step_size}"
    )
    raw_patch_dir = patch_root / "patches"
    features_root = args.results_root / "clam_features" / args.dataset / level_label

    if not args.skip_patching:
        process_list = None
        if not args.skip_preflight:
            process_list, _, _, _, _ = build_readable_slide_process_list(
                source_dir,
                patch_root,
                args.slide_ext,
                expected_slide_index,
            )

        cmd = [
            sys.executable,
            "create_patches_fp.py",
            "--source",
            str(source_dir),
            "--save_dir",
            str(patch_root),
            "--patch_size",
            str(args.patch_size),
            "--step_size",
            str(args.step_size),
            "--patch_level",
            str(args.patch_level),
            "--preset",
            "tcga.csv",
            "--seg",
            "--patch",
        ]
        if process_list is not None:
            cmd.extend(["--process_list", str(process_list)])
        if args.stitch:
            cmd.append("--stitch")
        run(cmd, cwd=args.clam_dir)

    env = os.environ.copy()
    sanitize_thread_env(env)
    uni_ckpt = args.checkpoints_root / "uni" / "pytorch_model.bin"
    titan_dir = args.checkpoints_root / 'TITAN'
    resnet50_ckpt = args.checkpoints_root / 'resnet50' / 'pytorch_model.bin'
    if uni_ckpt.exists():
        env['UNI_CKPT_PATH'] = str(uni_ckpt)
    if titan_dir.exists():
        env['TITAN_CKPT_DIR'] = str(titan_dir)
    if resnet50_ckpt.exists():
        env['RESNET50_CKPT_PATH'] = str(resnet50_ckpt)

    for encoder in args.encoders:
        target_patch_size = "448" if encoder == "conch_v1_5" else "224"
        feat_dir = features_root / encoder
        extract_cmd = [
            sys.executable,
            str(Path(__file__).with_name("extract_features_with_clam.py")),
            "--clam_dir",
            str(args.clam_dir),
            "--patch_h5_dir",
            str(raw_patch_dir),
            "--slide_dir",
            str(source_dir),
            "--feat_dir",
            str(feat_dir),
            "--model_name",
            encoder,
            "--slide_ext",
            args.slide_ext,
            "--batch_size",
            str(args.batch_size),
            "--target_patch_size",
            target_patch_size,
            "--num_workers",
            str(args.num_workers),
            "--device",
            args.device,
        ]
        if not args.no_amp:
            extract_cmd.append("--amp")
        extract_rc = run(extract_cmd, env=env, check=False)

        completion_rc = run(
            [
                sys.executable,
                str(Path(__file__).with_name("validate_feature_completion.py")),
                "--patch_h5_dir",
                str(raw_patch_dir),
                "--feat_dir",
                str(feat_dir),
            ],
            check=False,
        )
        if extract_rc != 0 or completion_rc != 0:
            raise RuntimeError(
                f"Feature extraction/validation failed for {encoder}: "
                f"extract_rc={extract_rc}, completion_rc={completion_rc}. "
                f"See {feat_dir / 'feature_extraction_stats.csv'} and "
                f"{feat_dir / 'feature_completion_report.csv'}"
            )

        run(
            [
                sys.executable,
                str(Path(__file__).with_name("validate_clam_features.py")),
                "--feat_dir",
                str(feat_dir),
                "--max_files",
                "3",
            ]
        )

    print("\nAll done.")
    print(f"patch root: {patch_root}")
    print(f"feature root: {features_root}")


if __name__ == "__main__":
    main()















